### ISSUE TITLE
Persisting boto3 session different s3_read / s3_write calls

### ISSUE THREAD

**Issue by DyfanJones** [daroczig/botor#13]
Hi all,
The helper read and write functions are really helpful when interacting with R and AWS S3. However there is a problem when it comes to reading / write large amount of files/R objects to AWS S3. If a the user has AWS KMS enabled on their AWS S3 bucket then AWS KMS is called each time s3_read/s3_write is used. This means the KMS could be called hundreds of times if s3_read/s3_write is put in a loop. If another boto_session or s3_client was passed as an parameter then the same session can be used over multiple calls to the function s3_read/s3_write. This should reduce a cost to AWS KMS dramatically.

```
# example of s3_read
s3_read(uri, fun, ..., extract = c("none", "gzip", "bzip2", "xz"), s3_client = s3())

# Example code in practise:
library(botor)
library(data.table)

# create s3 client
s3 <- s3()

# list files to be read:
s3_files <- s3_ls("s3://mybucket/my_files/")

# persisting s3 client session
df = rbindlist(lapply(s3_files$uri, s3_read, fun = fread, s3_client = s3))
```

**Comment by DyfanJones** [comment]
Hi all, 

It looks like the boto3 session persists through the use of package caching (which is really handy and neat :D )

https://github.com/daroczig/botor/blob/8eb24fa7f0102fbc88d9941dc097cb4016c930e5/R/botor.R#L73-L104


Forgive me if I am wrong but I can't find a way to update the cached boto3 objects. Is there a way to update these cached objects, or is this a feature not yet implemented?

**Comment by nfultz** [comment]
You should be able to get to the `clients` environment inside the package (probably using `:::`), and then you can read and write updated service objects to it.

**Comment by DyfanJones** [comment]
Thanks @nfultz, will close this ticket now :D
