### ISSUE TITLE
s3_ls function not working in CRAN version 0.3.0

### ISSUE THREAD

**Issue by somnaris** [daroczig/botor#15]
First of all, great idea to create an R-wrapper for boto3 to directly communicate with s3 within scripts!

I have found the s3_ls function not working in version 0.3.0 with R version 4.0.3 on Windows 10 (tested also in linux environments with same effect). The error message is:

> Error in data.frame(bucket_name = uri_parts$bucket_name, key = object$data$Key,  : 
  arguments imply differing number of rows: 1, 0

**Comment by somnaris** [comment]
Duplicate issue to #12. Using the source code from github fixed the issue.

**Comment by daroczig** [comment]
v0.4 was published to CRAN on 2023-03-12
