### ISSUE TITLE
's3_ls()' gives error when accessing a specific bucket

### ISSUE THREAD

**Issue by caarolinagil** [daroczig/botor#18]
Hi, 

I am trying to list all the objects in an S3 bucket so I can read them later but I get the following error:

![image](https://github.com/daroczig/botor/assets/118815321/dd9a8d8e-ac5c-4e1e-a8cf-55d8875b6d22)

My code is this one where I want to read the file with the most recent modification date and show too the structure of the bucket:

![image](https://github.com/daroczig/botor/assets/118815321/9ddf8943-08ac-4f00-8491-b3002abecb65)
![image](https://github.com/daroczig/botor/assets/118815321/7ca3fcae-ebf0-4764-826c-e0b7cfdf9457)

Thanks!

**Comment by gladkia** [comment]
👍

**Comment by marcin-kam** [comment]
@daroczig Can you please bump package version? Because CRAN version still has this bug

**Comment by daroczig** [comment]
@marcin-kam sure, just pushed a638922ba4ee93dac8e440a43808ed668521faf3

**Comment by marcin-kam** [comment]
Thank you!

**Comment by marcin-kam** [comment]
@daroczig Can you please push this update further? `botor` CRAN version is still 0.4.0

**Comment by seancuddz** [comment]
Hi all, @daroczig I am having difficulty picking up this fix on my version of botor, and so still get the error described above in s3_ls. Following instructions [here](https://user-guidance.analytical-platform.service.justice.gov.uk/appendix/botor.html#installation) on how to install botor leaves me with version 0.4.0, which does not seem to include the fix. I haven't been able to install a later version, eg trying renv::install("botor@0.4.0.9000"). Would you be able to assist with this please?

**Comment by daroczig** [comment]
@seancuddz see how to install dev version in the pkg readme: https://github.com/daroczig/botor?tab=readme-ov-file#installation

Anyway, I'm trying to get a new version to CRAN this week, thanks, folks.

**Comment by seancuddz** [comment]
Thanks @daroczig. I gave that a go but couldn't get that to work either. Pasted the error messages below in case helpful to you. Probably best to wait for the CRAN version so thanks for working to get that live.
```
remotes::install_github('daroczig/botor')
Downloading GitHub repo daroczig/botor@HEAD
* checking for file ‘/tmp/Rtmp0jmsnA/remotes19b5f1439af/daroczig-botor-47f21a2/DESCRIPTION’ ... OK
* preparing ‘botor’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘botor_0.4.0.9000.tar.gz’
Installing package into ‘/home/seancuddz/judicial_stats_processing/renv/library/R-4.4/x86_64-pc-linux-gnu’
(as ‘lib’ is unspecified)
Warning message:
Project requested R version '4.0.5' but '4.4.1' is currently being used 
* installing *source* package ‘botor’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
ERROR: lazy loading failed for package ‘botor’
* removing ‘/home/seancuddz/judicial_stats_processing/renv/library/R-4.4/x86_64-pc-linux-gnu/botor’
* restoring previous ‘/home/seancuddz/judicial_stats_processing/renv/library/R-4.4/x86_64-pc-linux-gnu/botor’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp0jmsnA/file19b379874f3/botor_0.4.0.9000.tar.gz’ had non-zero exit status
```

**Comment by darsoo** [comment]
Hi! 
When approximately can we expect the new version on CRAN?
Best!

**Comment by daroczig** [comment]
I spent a couple of hours cleaning up the package (CI/CD and related tooling was super outdated) and it should be ready for a new CRAN release. I'm running final tests, and planning to submit today 🤞

**Comment by daroczig** [comment]
CRAN release should be live soon 🎉 

> Dear maintainer,
> 
> thanks, package botor_0.4.1.tar.gz is on its way to CRAN.
> 
> Best regards,
> CRAN teams' auto-check service
> Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
> Check: *, Result: OK

**Comment by darsoo** [comment]
Many thanks!

**Comment by gladkia** [comment]
Thanks a lot!
