### ISSUE TITLE
`s3_ls` fails without a useful error if uri does not end in `/`

### ISSUE THREAD

**Issue by katrinabrock** [daroczig/botor#9]
Actual Behavior: `s3_ls("s3://my-bucket")` returns NULL in the case where `my_bucket` is valid. (ie `s3_ls("s3://my-bucket/")` would work)

My expectation would be that this would either work (returning a data frame of objects) or raise an error (similar to if the regex matching fails).

**Comment by daroczig** [comment]
Thanks a lot for the report, nice catch!
Can you please test the above fix?
